sudo: false
language: python
python:
- '2.7'
- '3.6'
install: pip install -r requirements.txt
before_script:
- pip install coverage
- pip install python-coveralls
- pip install pycodestyle
- npm install -g jshint
- cp travis-ci/manage.py manage.py
script:
- pycodestyle sis_provisioner/ --exclude=migrations,management,test
- jshint sis_provisioner/static/ --verbose
- coverage run --source=sis_provisioner/ manage.py test sis_provisioner
after_success:
- coveralls
