version: '2'

services:
  app:
    environment:
      - ENV=localdev
      - PORT=8000
      - AUTH=SAML_MOCK
    restart: always
    container_name: canvas_sis_provisioner
    build:
      context: .
    volumes:
      - ./sis_provisioner:/app/sis_provisioner
    ports:
      - "8000:8000"
