version: '3.4'

services:
  app:
    environment:
      ENV: localdev
      PORT: 8000
      AUTH: SAML_MOCK BLTI_DEV
    restart: always
    container_name: app-sis-provisioner
    build:
      context: .
      target: app-container
    volumes:
      - ./sis_provisioner:/app/sis_provisioner
    ports:
      - "8000:8000"
      - "8001:8001"
