ingress:
  enabled: true
  tls:
    canvas:
      secretName: test-apps.canvas.uw.edu-ingress-cert
      hosts:
        - test-apps.canvas.uw.edu
  hosts:
    canvas:
      host: test-apps.canvas.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
externalService:
  enabled: true
  name: canvas-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.28
  servicePort: 3306
database:
  engine: mysql
  name: sis_provisioner_test
  hostname: canvas-db-service
  secretName: test-apps.canvas.uw.edu-sql-secrets
repo: canvas
instance: test
image:
  repository: registry.hub.docker.com/acait/canvas
  tag: IMAGE_TAG
memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
gcsCredentials:
  mounted: true
  secretName: test-apps.canvas.uw.edu-gcs-credentials
cronjob:
  enabled: true
  jobs:
    - name: load-users
      schedule: "5 17 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["load_users"]
    - name: load-courses
      schedule: "5 18 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["load_courses"]
    - name: load-accounts
      schedule: "5 16 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["load_accounts"]
    - name: import-admins
      schedule: "55 12-23 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["import_admins", "--commit"]
daemon:
  enabled: true
  daemons:
    - name: monitor-imports
      replicaCount: 1
      command: ["/scripts/management_daemon.sh"]
      args: ["monitor_imports"]
    - name: import-courses-immediate
      replicaCount: 1
      command: ["/scripts/management_daemon.sh"]
      args: ["import_courses", "3", "--delay", "30"]
    - name: import-groups-immediate
      replicaCount: 1
      command: ["/scripts/management_daemon.sh"]
      args: ["import_groups", "3", "--delay", "30"]
certs:
  mounted: true
  certPath: /certs/test-apps.canvas.uw.edu-uwca.cert
  keyPath: /certs/test-apps.canvas.uw.edu-uwca.key
  secretName: test-apps.canvas.uw.edu-uwca-certs
environmentVariables:
  - name: ENV
    value: test

  - name: PWS_ENV
    value: EVAL

  - name: SWS_ENV
    value: EVAL
  - name: SWS_TIMEOUT
    value: "10"

  - name: GWS_ENV
    value: PROD
  - name: GWS_TIMEOUT
    value: "5"

  - name: KWS_ENV
    value: EVAL
  - name: KWS_TIMEOUT
    value: "5"
  - name: KWS_POOL_SIZE
    value: "5"

  - name: CANVAS_ENV
    value: EVAL
  - name: CANVAS_TIMEOUT
    value: "60"

  - name: ASTRA_ENV
    value: EVAL
  - name: ASTRA_APPLICATION
    value: Canvas

  - name: AUTH
    value: "SAML BLTI"
  - name: SAML_ENTITY_ID
    value: https://test-apps.canvas.uw.edu/saml2
  - name: CLUSTER_CNAME
    value: test-apps.canvas.uw.edu

externalSecrets:
  enabled: true
  secrets:
    - name: test-apps.canvas.uw.edu-shared-secrets
      externalKey: axdd/kv/data/canvas/shared/secrets
      data:
        - name: canvas-account-id
          property: canvas-account-id
        - name: continuum-account-id
          property: continuum-account-id
        - name: canvas-api-token
          property: canvas-api-token
        - name: lti-consumers
          property: lti-consumers
        - name: storage-bucket-name
          property: storage-bucket-name
        - name: storage-project-id
          property: storage-project-id
        - name: support-group-id
          property: support-group-id
        - name: admin-group-id
          property: admin-group-id
    - name: test-apps.canvas.uw.edu-gcs-credentials
      externalKey: axdd/kv/data/canvas/shared/gcs-credentials
      data:
        - name: credentials.json
          property: credentials.json
    - name: test-apps.canvas.uw.edu-secrets
      externalKey: axdd/kv/data/canvas/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: blti-aes-iv
          property: blti-aes-iv
        - name: blti-aes-key
          property: blti-aes-key
        - name: sqs-enrollment-key
          property: sqs-enrollment-key
        - name: sqs-enrollment-key-id
          property: sqs-enrollment-key-id
        - name: sqs-enrollment-queue-arn
          property: sqs-enrollment-queue-arn
        - name: sqs-group-key
          property: sqs-group-key
        - name: sqs-group-key-id
          property: sqs-group-key-id
        - name: sqs-group-queue-arn
          property: sqs-group-queue-arn
        - name: sqs-group-decrypt-key
          property: sqs-group-decrypt-key
        - name: sqs-instructoradd-key
          property: sqs-instructoradd-key
        - name: sqs-instructoradd-key-id
          property: sqs-instructoradd-key-id
        - name: sqs-instructoradd-queue-arn
          property: sqs-instructoradd-queue-arn
        - name: sqs-instructordrop-key
          property: sqs-instructordrop-key
        - name: sqs-instructordrop-key-id
          property: sqs-instructordrop-key-id
        - name: sqs-instructordrop-queue-arn
          property: sqs-instructordrop-queue-arn
        - name: sqs-person-key
          property: sqs-person-key
        - name: sqs-person-key-id
          property: sqs-person-key-id
        - name: sqs-person-queue-arn
          property: sqs-person-queue-arn
    - name: test-apps.canvas.uw.edu-sql-secrets
      externalKey: axdd/kv/data/canvas/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: test-apps.canvas.uw.edu-uwca-certs
      externalKey: axdd/kv/data/canvas/test/uwca-certs
      data:
        - name: test-apps.canvas.uw.edu-uwca.cert
          property: test-apps.canvas.uw.edu-uwca.cert
        - name: test-apps.canvas.uw.edu-uwca.key
          property: test-apps.canvas.uw.edu-uwca.key
    - name: test-apps.canvas.uw.edu-ic-certs
      externalKey: axdd/kv/data/canvas/test/ic-certs
      data:
        - name: test-apps.canvas.uw.edu-ic.cert
          property: test-apps.canvas.uw.edu-ic.cert
    - name: test-apps.canvas.uw.edu-uw-idp-cert
      externalKey: axdd/kv/data/idp-cert
      data:
        - name: uw-idp-cert
          property: cert
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: django-secret
  canvasAPIToken:
    name: CANVAS_OAUTH_BEARER
    secretName: test-apps.canvas.uw.edu-shared-secrets
    secretKey: canvas-api-token
  canvasAccountID:
    name: CANVAS_ACCOUNT_ID
    secretName: test-apps.canvas.uw.edu-shared-secrets
    secretKey: canvas-account-id
  continuumAccountID:
    name: CONTINUUM_ACCOUNT_ID
    secretName: test-apps.canvas.uw.edu-shared-secrets
    secretKey: continuum-account-id
  supportGroup:
    name: SUPPORT_GROUP
    secretName: test-apps.canvas.uw.edu-shared-secrets
    secretKey: support-group-id
  adminGroup:
    name: ADMIN_GROUP
    secretName: test-apps.canvas.uw.edu-shared-secrets
    secretKey: admin-group-id
  enrollmentQueueArn:
    name: SQS_ENROLLMENT_QUEUE_ARN
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-enrollment-queue-arn
  enrollmentKeyId:
    name: SQS_ENROLLMENT_KEY_ID
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-enrollment-key-id
  enrollmentKey:
    name: SQS_ENROLLMENT_KEY
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-enrollment-key
  groupQueueArn:
    name: SQS_GROUP_QUEUE_ARN
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-group-queue-arn
  groupKeyId:
    name: SQS_GROUP_KEY_ID
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-group-key-id
  groupKey:
    name: SQS_GROUP_KEY
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-group-key
  groupDecryptKey:
    name: SQS_GROUP_DECRYPT_KEY
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-group-decrypt-key
  personQueueArn:
    name: SQS_PERSON_QUEUE_ARN
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-person-queue-arn
  personKeyId:
    name: SQS_PERSON_KEY_ID
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-person-key-id
  personKey:
    name: SQS_PERSON_KEY
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-person-key
  instructorAddQueueArn:
    name: SQS_INSTRUCTOR_ADD_QUEUE_ARN
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-instructoradd-queue-arn
  instructorAddKeyId:
    name: SQS_INSTRUCTOR_ADD_KEY_ID
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-instructoradd-key-id
  instructorAddKey:
    name: SQS_INSTRUCTOR_ADD_KEY
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-instructoradd-key
  instructorDropQueueArn:
    name: SQS_INSTRUCTOR_DROP_QUEUE_ARN
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-instructordrop-queue-arn
  instructorDropKeyId:
    name: SQS_INSTRUCTOR_DROP_KEY_ID
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-instructordrop-key-id
  instructorDropKey:
    name: SQS_INSTRUCTOR_DROP_KEY
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: sqs-instructordrop-key
  BLTIAESKey:
    name: BLTI_AES_KEY
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: blti-aes-key
  BLTIAESIV:
    name: BLTI_AES_IV
    secretName: test-apps.canvas.uw.edu-secrets
    secretKey: blti-aes-iv
  LTIConsumers:
    name: LTI_CONSUMERS
    secretName: test-apps.canvas.uw.edu-shared-secrets
    secretKey: lti-consumers
  storageBucketName:
    name: STORAGE_BUCKET_NAME
    secretName: test-apps.canvas.uw.edu-shared-secrets
    secretKey: storage-bucket-name
  storageProjectId:
    name: STORAGE_PROJECT_ID
    secretName: test-apps.canvas.uw.edu-shared-secrets
    secretKey: storage-project-id
  samlSPCert:
    name: SP_CERT
    secretName: test-apps.canvas.uw.edu-ic-certs
    secretKey: test-apps.canvas.uw.edu-ic.cert
  samlIDPCert:
    name: IDP_CERT
    secretName: test-apps.canvas.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
