# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0006_auto_20160708_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='reg_id',
            field=models.CharField(default='NONE', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='import',
            name='canvas_progress',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='import',
            name='monitor_status',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='post_status',
            field=models.SmallIntegerField(null=True),
        ),
    ]
