# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0009_import_canvas_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='updated_overrides_date',
            field=models.DateTimeField(null=True),
        ),
    ]
