# Generated by Django 2.1 on 2018-10-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0012_auto_20180417_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('sdb', 'SDB'), ('adhoc', 'Ad Hoc'), ('root', 'Root'), ('test', 'Test')], max_length=16),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('sdb', 'SDB'), ('adhoc', 'Ad Hoc')], max_length=16),
        ),
        migrations.AlterField(
            model_name='course',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, 'none'), (1, 'normal'), (2, 'high'), (3, 'immediate')], default=1),
        ),
        migrations.AlterField(
            model_name='coursemember',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, 'none'), (1, 'normal'), (2, 'high'), (3, 'immediate')], default=0),
        ),
        migrations.AlterField(
            model_name='coursemember',
            name='type',
            field=models.SlugField(choices=[('uwnetid', 'UWNetID'), ('eppn', 'ePPN')], max_length=16),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, 'none'), (1, 'normal'), (2, 'high'), (3, 'immediate')], default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, 'none'), (1, 'normal'), (2, 'high'), (3, 'immediate')], default=1),
        ),
        migrations.AlterField(
            model_name='import',
            name='csv_type',
            field=models.SlugField(choices=[('account', 'Curriculum'), ('user', 'User'), ('course', 'Course'), ('unused_course', 'Term'), ('coursemember', 'CourseMember'), ('enrollment', 'Enrollment'), ('group', 'Group')], max_length=20),
        ),
        migrations.AlterField(
            model_name='import',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, 'none'), (1, 'normal'), (2, 'high'), (3, 'immediate')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='net_id',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, 'none'), (1, 'normal'), (2, 'high'), (3, 'immediate')], default=1),
        ),
    ]
