# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.0.13 on 2019-03-04 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0014_auto_20190207_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='account_id',
            new_name='account_id_str',
        ),
        migrations.AddField(
            model_name='admin',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_provisioner.Account'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='account_id_str',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='canvas_id',
            field=models.IntegerField(null=True),
        ),
    ]
