# Generated by Django 2.0.13 on 2019-04-19 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0016_auto_20190328_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_data', models.TextField()),
                ('time_saved', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_provisioner.Account')),
            ],
            options={
                'get_latest_by': 'time_saved',
            },
        ),
    ]
