# Generated by Django 2.0.13 on 2019-05-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0017_rolecache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltool',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_provisioner.Account'),
        ),
        migrations.DeleteModel(
            name='ExternalToolAccount',
        ),
    ]
