# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.0.13 on 2019-06-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0018_auto_20190520_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltool',
            name='queue_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
