# Generated by Django 2.2.19 on 2021-04-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0019_externaltool_queue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invalid_enrollments_deleted_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invalid_enrollments_found_date',
            field=models.DateTimeField(null=True),
        ),
    ]
