# Generated by Django 2.0.13 on 2019-10-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0019_externaltool_queue_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseMember',
        ),
        migrations.AlterField(
            model_name='import',
            name='csv_type',
            field=models.SlugField(choices=[('account', 'Curriculum'), ('admin', 'Admin'), ('user', 'User'), ('course', 'Course'), ('unused_course', 'Term'), ('enrollment', 'Enrollment'), ('group', 'Group')], max_length=20),
        ),
    ]
