# Generated by Django 2.2.21 on 2021-05-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0020_auto_20210422_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidenrollment',
            name='restored_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='invalid_enrollment_check_required',
            field=models.BooleanField(default=False),
        ),
    ]
