# Generated by Django 2.2.20 on 2021-04-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0020_auto_20210409_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseMember',
        ),
        migrations.AlterField(
            model_name='import',
            name='csv_type',
            field=models.SlugField(choices=[('account', 'Curriculum'), ('admin', 'Admin'), ('user', 'User'), ('course', 'Course'), ('unused_course', 'Term'), ('enrollment', 'Enrollment'), ('group', 'Group')], max_length=20),
        ),
    ]
