# Generated by Django 3.2.16 on 2023-01-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0021_auto_20210504_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRetention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_course_id', models.IntegerField(unique=True)),
                ('sis_course_id', models.CharField(max_length=80, null=True)),
                ('creation_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('deletion_date', models.DateTimeField(null=True)),
                ('exception_granted_date', models.DateTimeField(null=True)),
                ('exception_granted_by', models.CharField(max_length=32, null=True)),
                ('exception_desc', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
