# Generated by Django 3.2.17 on 2023-02-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0022_auto_20230130_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseMember',
        ),
        migrations.AlterField(
            model_name='course',
            name='canvas_course_id',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
