# Generated by Django 3.2.18 on 2023-04-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0023_auto_20230213_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='duplicate_code',
            field=models.CharField(default='', max_length=2),
        ),
    ]
