# Generated by Django 4.2.9 on 2024-01-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0025_alter_import_csv_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnusedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='import',
            name='csv_type',
            field=models.SlugField(choices=[('account', 'sis_provisioner.models.account.Curriculum'), ('admin', 'sis_provisioner.models.admin.Admin'), ('user', 'sis_provisioner.models.user.User'), ('course', 'sis_provisioner.models.course.Course'), ('expired_course', 'sis_provisioner.models.course.ExpiredCourse'), ('unused_course', 'sis_provisioner.models.course.UnusedCourse'), ('enrollment', 'sis_provisioner.models.enrollment.Enrollment'), ('invalid_enrollment', 'sis_provisioner.models.enrollment.InvalidEnrollment'), ('group', 'sis_provisioner.models.group.Group')], max_length=20),
        ),
    ]
