# Generated by Django 5.2.7 on 2025-10-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0026_unusedcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='override_sis_stickiness',
            field=models.BooleanField(default=False),
        ),
    ]
