# Generated by Django 5.2.17 on 2026-09-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0027_override_sis_stickiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
